name: basic code checks
on: [pull_request]

jobs:
  run:
    name: Editor config check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41
    - uses: cachix/install-nix-action@v25
    - run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          nix run nixpkgs#editorconfig-checker -- $file
        done
