name: basic code checks
on: [pull_request]

jobs:
  run:
    name: Editor config check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: files
      uses: jitterbit/get-changed-files@v1
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: workflow/nix-shell-action@v3
      with:
        packages: editorconfig-checker
        script: |
          editorconfig-checker -disable-indent-size ${{ steps.files.outputs.all }}
    - if: ${{ failure() }}
      run: |
        echo "::error :: Hey! It looks like your changes don't follow our editorconfig settings."
