name: update flake.lock
on:
  schedule:
    # Run every 1st of the month at 12:00
    - cron:  '* 12 1 * *'
  workflow_dispatch:

jobs:
  update-flake-lock:
    name: update flake.lock
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      # Install Nix on the runner
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
        # Checkout of the current head in the working dir
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Update flake
        run: |
          nix --experimental-features 'nix-command flakes' flake update
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -m "update flake.lock" flake.lock
      - name: Open Pull request
        run: |
          git push origin master:flake-lock-update
          gh pr create -B master -H flake-lock-update --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'

