name: basic nix checks
on: [pull_request]

jobs:
  run:
    name: nix-instantiate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: files
      uses: jitterbit/get-changed-files@v1
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        nix-instantiate release.nix -A qchem


