name: basic nix checks
on: [pull_request]

jobs:
  run1:
    name: nix-instantiate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: files
      uses: jitterbit/get-changed-files@v1
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        nix-instantiate release.nix -A qchem
  run2:
    name: statix code check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: files
      uses: jitterbit/get-changed-files@v1
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: run statix on changed files
      uses: workflow/nix-shell-action@v3
      with:
        packages: statix
        script: |
          for file in ${{ steps.files.outputs.all }}; do
            statix check $file
          done

