name: rebuilds
on: [pull_request]

jobs:
  # Calculate changed derivations
  get-changed-derivs:
    name: Get changed derivations
    runs-on: ubuntu-latest
    steps:
      # Install Nix on the runner
      - uses: cachix/install-nix-action@v20
      # Pull from the cachix cache
      - uses: cachix/cachix-action@v12
        with:
          name: nix-qchem
      # Checkout of the current head in the working dir
      - uses: actions/checkout@v3
      # Get PR target branch checkout
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          repository: ${{ github.event.pull_request.base.repo.full_name }}
          path: pr_base
      # Get a checkout of this PR
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          path: pr_head
      # Calculate changed derivations and upload as artifacts
      - run: nix eval --impure --expr 'import ./.github/workflows/changedPaths.nix ./pr_head ./pr_base' --json | tee chDerivs.json
      # Upload JSON of the changed derivations
      - uses: actions/upload-artifact@v3
        with:
          name: Changed-Derivations
          path: chDerivs.json
          retention-days: 1

  # Rebuild changed derivations for the pinned snapshot
  rebuild-pin:
    name: Pinned
    needs: get-changed-derivs
    runs-on: ubuntu-latest
    steps:
      # Install Nix on the runner
      - uses: cachix/install-nix-action@v20
      # Pull from the cachix cache
      - uses: cachix/cachix-action@v12
        with:
          name: nix-qchem
      # Checkout of the current head in the working dir
      - uses: actions/checkout@v3
      # Get changed derivations as artifact from previous step
      - uses: actions/download-artifact@v3
        with:
          name: Changed-Derivations
      # Rebuild all changed python3 packages
      - run: nix build --accept-flake-config $(for p in $(jq '.python3[]' chDerivs.json | tr -d "\""); do echo ".#python3.pkgs.${p}"; done)
      # Rebuild all changed top-level packages
      - run: nix build --accept-flake-config $(for p in $(jq '.topLevel[]' chDerivs.json | tr -d "\""); do echo ".#${p}"; done)

  # Rebuild changed derivations for nixpkgs-unstable
  rebuild-unstable:
    name: Unstable
    needs: get-changed-derivs
    runs-on: ubuntu-latest
    steps:
      # Install Nix on the runner
      - uses: cachix/install-nix-action@v20
      # Pull from the cachix cache
      - uses: cachix/cachix-action@v12
        with:
          name: nix-qchem
      # Checkout of the current head in the working dir
      - uses: actions/checkout@v3
      # Get changed derivations as artifact from previous step
      - uses: actions/download-artifact@v3
        with:
          name: Changed-Derivations
      # Rebuild all changed python3 packages
      - run: nix build --accept-flake-config --override-input nixpkgs nixpkgs/nixpkgs-unstable $(for p in $(jq '.python3[]' chDerivs.json | tr -d "\""); do echo ".#python3.pkgs.${p}"; done)
      # Rebuild all changed top-level packages
      - run: nix build --accept-flake-config --override-input nixpkgs nixpkgs/nixpkgs-unstable $(for p in $(jq '.topLevel[]' chDerivs.json | tr -d "\""); do echo ".#${p}"; done)

  # Rebuild changed derivations for nixpkgs/master
  rebuild-master:
    name: Master
    needs: get-changed-derivs
    runs-on: ubuntu-latest
    steps:
      # Install Nix on the runner
      - uses: cachix/install-nix-action@v20
      # Pull from the cachix cache
      - uses: cachix/cachix-action@v12
        with:
          name: nix-qchem
      # Checkout of the current head in the working dir
      - uses: actions/checkout@v3
      # Get changed derivations as artifact from previous step
      - uses: actions/download-artifact@v3
        with:
          name: Changed-Derivations
      # Rebuild all changed python3 packages
      - run: nix build --accept-flake-config --override-input nixpkgs nixpkgs/master $(for p in $(jq '.python3[]' chDerivs.json | tr -d "\""); do echo ".#python3.pkgs.${p}"; done)
      # Rebuild all changed top-level packages
      - run: nix build --accept-flake-config --override-input nixpkgs nixpkgs/master $(for p in $(jq '.topLevel[]' chDerivs.json | tr -d "\""); do echo ".#${p}"; done)
