name: nix rebuilds
on: [pull_request]

jobs:
  run:
    name: Calculate changed outputs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: pr
    - uses: actions/checkout@v2
      with:
        path: master
        ref: master
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Changed paths
      run: |
        cat /etc/nix/nix.conf
        id
        echo $NIX_PATH
        nix-channel --add https://nixos.org/channels/nixos-21.11 nixpkgs
        nix-channel --update
        nix-instantiate ./pr/release.nix -A qchem
        nix-env -f ./pr/release.nix -qaP --no-name --out-path --show-trace \
          --option binary-caches 'https://cache.nixos.org/ https://nix-qchem.cachix.org/' \
          --option trusted-public-keys '
            nix-qchem.cachix.org-1:ZjRh1PosWRj7qf3eukj4IxjhyXx6ZwJbXvvFk3o3Eos=
            cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          ' --arg allowUnfree false -A qchem | sort > paths-pr
        nix-instantiate ./master/release.nix -A qchem
        nix-env -f ./master/release.nix -qaP --no-name --out-path --show-trace \
          --option binary-caches 'https://cache.nixos.org/ https://nix-qchem.cachix.org/' \
          --option trusted-public-keys '
            nix-qchem.cachix.org-1:ZjRh1PosWRj7qf3eukj4IxjhyXx6ZwJbXvvFk3o3Eos=
            cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          ' --arg allowUnfree false -A qchem | sort > paths-master
        diff -u paths-master paths-pr | grep -E "^\+" | sed '/^+++/d; s/^+//' | tee > changed_outputs
        echo "The following outputs need to be rebuild:" > changed_outputs.md
        awk '{ print $1 }' changed_outputs | sed 's/\(.*\)/- \1/' >> changed_outputs.md
    - uses: machine-learning-apps/pr-comment@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: changed_outputs.md
