name: basic code checks
on: [pull_request]

jobs:
  run:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: files
      uses: jitterbit/get-changed-files@v1
    - name: fix files
      id: changed_files
      run: |
        echo "::set-output name=all::$(echo "${{ steps.files.outputs.all }}" | tr ' ' '\n' | sed 's:\(.*\):./\1:' | tr '\n' ' ')"
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: check for typos
      uses: workflow/nix-shell-action@v1
      with:
        packages: typos
        script: |
          typos $(echo "${{ steps.files.outputs.all }}" | tr ' ' '\n' | sed 's:\(.*\):./\1:' | tr '\n' ' ')

