name: basic spell checks
on: [pull_request]

jobs:
  run:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
    - uses: cachix/install-nix-action@v20
    - run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          nix run nixpkgs#typos -- $(echo "${{ steps.files.outputs.all }}" | tr ' ' '\n' | sed 's:\(.*\):./\1:;/\.patch$/d' | tr '\n' ' ')
        done

