name: basic spell checks
on: [pull_request]

jobs:
  run:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41
    - uses: cachix/install-nix-action@v20
    - run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          # exclude patches and input files
          if [[ ! "$file" =~ .patch$ && ! "$file" =~ .inp$ ]]; then
            nix run nixpkgs#typos -- "$file"
          fi
        done

