name: basic code checks
on: [pull_request]

jobs:
  run:
    name: Spell check changes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2
    - name: Changed files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: typos-action
      uses: crate-ci/typos@v1.0.4
      with:
        files: ${{ steps.files.outputs.all }}

