name: basic code checks
on: [pull_request]

jobs:
  run:
    name: Spell check changes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2
    - name: Changed files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: fix files
      id: changed_files
      run: |
        echo "::set-output name=all::$(echo "${{ steps.files.outputs.all }}" | tr ' ' '\n' | sed 's:\(.*\):./\1:' | tr '\n' ' ')"
        echo "${{ steps.files.outputs.all }}" | tr ' ' '\n' | sed 's:\(.*\):./\1:' | tr '\n' ' '
    - name: typos-action
      uses: crate-ci/typos@v1.0.4
      with:
        files: ${{ steps.changed_files.outputs.all }}

